server:
  port: 8009

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/taskdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: secret

jpa:
  hibernate:
    ddl-auto: update
  open-in-view: false
